### ISSUE TITLE
Docker images for benchmarking

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssl#10]
It would be nice to have a Docker image for automatic benchmarking of liboqs-based ciphersuites in this OpenSSL fork.

**Comment by Coen-Schuijt** [comment]
Please take a look at https://github.com/Coen-Schuijt/liboqs-benchmarks

**Comment by dstebila** [comment]
Hi Coen-Schuijt! Thanks for doing this -- looks really great!  This week we're all focused on getting a release out the door, but we'll be able to take a look at that starting next week.

**Comment by dstebila** [comment]
Sorry for the delay in getting back to you.  We finished our release last week and are now ready to work on the next phase. Getting Docker images for testing a variety of things -- including benchmarking -- is next for us.  My colleague Shravan @smashra is taking the lead for us on this right now.  I've asked Shravan to take a look at this and follow up.

**Comment by baentsch** [comment]
@dstebila @smashra I just noticed this issue and would like to ask whether anything beyond the above has happened? If not, please take a look at this PR: https://github.com/open-quantum-safe/testing/pull/34 and the docker images "falling out" (on hub.docker.com -> openqsafe): They have the openssl `speed` option easily exposed so that one only needs to pass the QSC algorithm to test as parameter, e.g., `docker run -it openqsafe/liboqs-ubuntu-bionic-run oqs-speedtest dilithium4 kyber1024`(does CA&server key gen and runs s_server and client (`s_time` option)).

**Comment by dstebila** [comment]
It's been my intention to update `openssl speed` in OpenSSL 1.1.1 to have this functionality for some time (we had it in OpenSSL 1.0.2, but never did it in 1.1.1).  We haven't followed up on this issue since last year, unfortunately.

**Comment by baentsch** [comment]
@dstebila We have [openssl speed](https://github.com/open-quantum-safe/openssl#speed) and [docker-based perf testing](https://github.com/open-quantum-safe/oqs-demos/tree/master/curl#performance-testing) now -- so shouldn't we close this?
