### ISSUE TITLE
PKCS7 Support for OQS Algorithms

### ISSUE THREAD

**Issue by panburana** [open-quantum-safe/openssl#118]
I'm interested in using the signature algorithms from liboqs thru OpenSSL's PKCS7 interface. Through some experimentation, I've noticed that for the OQS algorithms, an oqs_pkey_ctrl() function that handles the ASN1_PKEY_CTRL_PKCS7_SIGN operation isn't defined in oqs_meth.c as has been done for classical algorithms such as in rsa_ameth.c or ec_ameth.c. I blindly wrote a crude  implementation of that function to see what else fails with generating a PKCS7 signature with an quantum safe signature algorithm and I hit a lot of issues with OpenSSL's PKCS7 code not handling a NULL digest associated with OQS private keys. 

Could someone provide some background on why PKCS7 support with OQS along wasn't done (totally understand if it wasn't a priority) as it seems a lot of the core ASN1 calls were implemented in oqs_meth.c or if there is some gating technical reason that would make this work a challenge?

**Comment by dstebila** [comment]
Hi Peter, our initial focus was on demonstrating authentication in TLS, so we just implemented the minimum we needed in order to do so (generate certs using command line tools, use them in TLS).  We didn't delve into the S/MIME, CMS, PKCS 7, etc. territory.  If you are interested to work on that, we're certainly happy to accept code in that area.

**Comment by panburana** [comment]
Thanks for clarifying! At minimum, I'd be more than happy to write up what I've encountered.

**Comment by dstebila** [comment]
That would be great, and helpful to someone else trying to enable that functionality.
