### ISSUE TITLE
Add more algorithms from liboqs

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssl#144]
- [x] Kyber 90s
- [x] LEDAkem
- [x] ThreeBears
- [ ] HQC (https://github.com/open-quantum-safe/liboqs/issues/709)

**Comment by dstebila** [comment]
See https://github.com/open-quantum-safe/openssl/wiki/Contributing-Guide

**Comment by baentsch** [comment]
Quick understanding question: (Why) Do we truly still (need to?) maintain the 'curve ID' in the `oqs-template/generate.yml` file? If I understand it right, those 'nids' have no relationship whatsoever with the true NIDs (which are generated by the `crypto/objects/obj_mac.num` generator in combination with the openssl `make generate_crypto_objects` script) and which in all other places are referenced by #defines, right? 

--> Anything speaking against dropping them (in favour of using the true NIDs)? As the structure of openssl has changed (evp_int.h, asn1_int.h gone, ssl_locl.h renamed) since the last time the tool was run, we anyway have to touch more things than just `generate.yml`....

**Comment by baentsch** [comment]
@dstebila The closing happened automatically on Merge.... Should we keep this open until HQC is fixed and integrated?

**Comment by xvzcf** [comment]
> Quick understanding question: (Why) Do we truly still (need to?) maintain the 'curve ID' in the `oqs-template/generate.yml` file? If I understand it right, those 'nids' have no relationship whatsoever with the true NIDs (which are generated by the `crypto/objects/obj_mac.num` generator in combination with the openssl `make generate_crypto_objects` script) and which in all other places are referenced by #defines, right?
> 
> --> Anything speaking against dropping them (in favour of using the true NIDs)? As the structure of openssl has changed (evp_int.h, asn1_int.h gone, ssl_locl.h renamed) since the last time the tool was run, we anyway have to touch more things than just `generate.yml`....

The NIDs in `obj_mac.num` are OpenSSL-internal identifiers. The curve IDs in the `generate.yml` file are TLS 1.3 (private-use) identifiers, and are referenced [here](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/ssl/ssl_local.h#L480) and [here](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/ssl/t1_trce.c#L536) for example.

**Comment by baentsch** [comment]
@xvzcf Thanks for the pointers. The first use I was aware of, the second eluded me. I'd then consider this PR truly closed.
