### ISSUE TITLE
PQ ciphers in pyopenssl and cryptography

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/openssl#201]
Hello, first off this is not an issue but a question. I have been working with pqopenssl for a while now but currently, I am working on a project that would need PQ integration with pyopenssl and cryptography (Python). How should I go about doing this?

**Comment by baentsch** [comment]
Hello -- thanks for your interest in/use of OQS. First off, can I safely assume you saw https://github.com/open-quantum-safe/liboqs-python and it doesn't provide what you need? If so, could you help me understand what you cannot do with the presently available "set of things" (liboqs -> oqs-py-binding and oqs-openssl -> app-level support like [curl](https://github.com/open-quantum-safe/oqs-demos/tree/master/curl) )? Do you "simply" want to establish TLS 1.3 QSC connections from within Python? If so, did you try oqs-curl with http://pycurl.io/docs/latest/index.html ? Just a thought, I also didn't try that yet.

**Comment by prchander** [comment]
Hello, thank you for your reply. Yes, I did check out the python liboqs but that does not really help with what I am trying to do. The project is to include post-quantum ciphers in QUIC (An internet protocol alternative to TCP/TLS). It does use TLS 1.3 but I am trying to figure out how python cryptography and python OpenSSL can be modified to interpret PQ ciphers.

**Comment by baentsch** [comment]
Thanks for the background. This looks like you'd need a pretty "deep" integration of TLS and QUIC state machines for which there is arguably much better support in C (e.g., [QUIC in curl](https://daniel.haxx.se/blog/tag/quic/) ) -- assuming (quantum-safe) functionality is more important than use of Python. Otherwise, why don't you build off https://pypi.org/project/aioquic/ ? 

But then again, this is your project and I wouldn't want/can't define the direction your work should take. Suffice it to say that our work was intended to show QSC-integration into a TLS engine -- without necessarily the goal to make the result ready-to-use for "language-specific" state-machine integrations with other protocols.

**Comment by prchander** [comment]
Thank you for your reply. I am building from aioquic but I am just not sure where to start integrating. It uses openssl so I am just thinking linking pip to OQS-OpenSSL should do the trick right?

**Comment by baentsch** [comment]
Sorry I only see this question now -- and I have to admit I don't understand it: For all I know (but I may be wrong) there is no pip-deployed oqs-openssl. I'm afraid you'll have to build oqs-openssl yourself (or use a ready-built container like https://hub.docker.com/r/openquantumsafe/curl-dev ).

**Comment by baentsch** [comment]
@prchander: Usual 'close' notification after some time of inactivity on an issue. Please re-open if you see a need.
