### ISSUE TITLE
Question on the signing process

### ISSUE THREAD

**Issue by hengyongming** [open-quantum-safe/openssl#329]
Hi, 

I am wondering how signing takes place in oqs?

These are 2 possible ways that I came up with but I am unsure whether it is the correct idea ?

Method A

Step 1) Data m -> SHA2(m) -> PQSign(SHA2(m)) = S1

Step 2) Data m -> SHAX(m) -> RSASign(SHAX(m)) = S2, where X = 256 / 384 / 512

Method B

Step 1) Data m -> SHA2(m) -> PQSign(SHA2(m)) = S1

Step 2) SHA2(m) -> SHAX(SHA2(m)) -> RSASign(SHAX(SHA2(m))) = S3, where X = 256 / 384 / 512

Do correct me if I am wrong.
Thank you in advance!

**Comment by friedrichsenm** [comment]
(Note, I'm not one of the OQS folks). Do you mean a signature in a certificate or as part of authentication in a TLS connection? [This part of the wiki](https://github.com/open-quantum-safe/openssl/wiki/Integrating-PQC-into-TLS-1.3) talks about how they integrated things in more detail, but it looks like if you sign things with just a straight PQ algorithm (not hybrid), there is no hashing done to the message before passing to the signature algorithm.

I've been playing around with Falcon signatures and it looks like there is some hashing done with SHA3 internally, so maybe that's why no hashing is done prior to calling the signing API.

**Comment by dstebila** [comment]
@friedrichsenm's explanation is right for PQ-only signing.  "Hybrid" signing, where both PQ and non-PQ (e.g., RSA) are used, takes the form of

- Data m -> PQSign(m) = s1
- Data m -> RSASign(m) = s2
- Signatures is s1 || s2

The signature algorithm itself is responsible for hashing long messages to short digests internally.

**Comment by hengyongming** [comment]
@friedrichsenm @dstebila Thanks for the help! Just a follow-up question: Is the way of hybrid signing you mentioned above the SAME for both generating hybrid signature in a certificate and hybrid signing messages for authentication?  I guess so but would like to get your confirmation.

Thanks in advance!

**Comment by baentsch** [comment]
It is. Code is [here](https://github.com/open-quantum-safe/openssl/blob/8c93484150cb30debce06db7289c563d97eaafdb/crypto/ec/oqs_meth.c#L1431-L1535).
