### ISSUE TITLE
Must include LIBOQS_DOCS_DIR in environment

### ISSUE THREAD

**Issue by samyuktha123sets** [open-quantum-safe/openssl#353]
I am trying to enable the 'SPHINCSSHAKE256128FSIMPLE' variant. I have enabled it in the generate.yml file. When I run 'python3 oqs-template/generate.py' from the openssl directory . I face this error 'Must include LIBOQS_DOCS_DIR in environment'

**Comment by baentsch** [comment]
This precisely means what it says: In order to run `generate.py` successfully, it needs to know the location of the docs directory of `liboqs`. Thus you need to set `LIBOQS_DOCS_DIR` accordingly before, e.g. via `export LIBOQS_DOCS_DIR=/full-path/to/liboqs/docs` (obviously replace the first two path elements with where you have placed the `liboqs` source code tree).
