### ISSUE TITLE
How to avoid copying liboqs include and lib files to the oqs/ subdirectory

### ISSUE THREAD

**Issue by fwh-dc** [open-quantum-safe/openssl#431]
Hi,

I am integrating oqs-openssl in a larger cmake project where liboqs is already built and linked to another library. I want to avoid copying the liboqs library file and header files to the oqs/ subdirectory and instead rely on -I and -L flags. 
But when I try to do that I get into trouble because the build process requires the liboqs library and header files to be present in the oqs subdirectory.

Is there any way to successfully build and install oqs-openssl without copying liboqs library and header files to the oqs/ subfolder?

Regards,
Frederik

**Comment by baentsch** [comment]
Hi Frederik, the most simple answer you probably already tried: Create soft links. Otherwise, I don't see a way (to satisfy `autoconf`). FWIW, these dependency issues were one of the reasons why we started creating [oqs-provider](https://github.com/open-quantum-safe/oqs-provider): When built, it's completely self-contained and delivers PQ algs via OpenSSL(3) to its apps. Also, it's a "native" `cmake` project like `liboqs`...

**Comment by fwh-dc** [comment]
Hi,

Thanks for the quick reply.
Great tip to use oqs-provider! I'll have a look at it.
